Check for success of qconf -au

diff --git a/createThomasuser b/createThomasuser
--- a/createThomasuser
+++ b/createThomasuser
@@ -75,7 +75,11 @@ if [ "${become_output:0:6}" != "Beacon" ]; then
 fi
 
 # add user to ACL so they can log in and submit jobs
-qconf -au "$username" "$ACL"
+if ! qconf -au "$username" "$ACL"
+then
+  echo "Adding ${username} to $ACL ACL failed, exiting." 
+  exit 1
+fi
 
 # check that the qconf change actually worked!
 # Try 3 times.
diff --git a/createYounguser b/createYounguser
--- a/createYounguser
+++ b/createYounguser
@@ -77,12 +77,16 @@ fi
 # replacement for become - creates homedir and adds key
 if ! sudo /shared/ucl/sysops/libexec/add_sshkeys "${username}" "${ssh_key}"
 then
-  echo "Creation of "${username}" homedir or addition of key failed, exiting."
+  echo "Creation of ${username} homedir or addition of key failed, exiting."
   exit 1
 fi
 
 # add user to ACL so they can log in and submit jobs
-qconf -au $username $ACL
+if ! qconf -au "$username" "$ACL"
+then
+  echo "Adding ${username} to $ACL ACL failed, exiting."
+  exit 1
+fi
 
 # check that the qconf change actually worked!
 # Try 3 times.
