Output ye errors to stderr.

diff --git a/createMichaeluser b/createMichaeluser
--- a/createMichaeluser
+++ b/createMichaeluser
@@ -77,14 +77,14 @@ fi
 # replacement for become - creates homedir and adds key
 if ! sudo /shared/ucl/sysops/libexec/add_sshkeys "${username}" "${ssh_key}"
 then
-  echo "Creation of ${username} homedir or addition of key failed, exiting."
+  echo "Creation of ${username} homedir or addition of key failed, exiting." >&2
   exit 1
 fi
 
 # add user to ACL so they can log in and submit jobs
 if ! qconf -au "$username" "$ACL"
 then
-  echo "Adding ${username} to $ACL ACL failed, exiting."
+  echo "Adding ${username} to $ACL ACL failed, exiting." >&2
   exit 1
 fi
 
@@ -103,7 +103,7 @@ do
   then
     sleep 5
   else
-    echo "Grid Engine failed to add ${username} to $ACL ACL three times - please contact rc-support@ucl.ac.uk"
+    echo "Grid Engine failed to add ${username} to $ACL ACL three times - please contact rc-support@ucl.ac.uk" >&2
     exit 1
   fi
 done
diff --git a/createThomasuser b/createThomasuser
--- a/createThomasuser
+++ b/createThomasuser
@@ -77,7 +77,7 @@ fi
 # add user to ACL so they can log in and submit jobs
 if ! qconf -au "$username" "$ACL"
 then
-  echo "Adding ${username} to $ACL ACL failed, exiting." 
+  echo "Adding ${username} to $ACL ACL failed, exiting." >&2 
   exit 1
 fi
 
@@ -96,7 +96,7 @@ do
   then 
     sleep 5
   else
-    echo "Grid Engine failed to add ${username} to $ACL ACL three times - please contact rc-support@ucl.ac.uk"
+    echo "Grid Engine failed to add ${username} to $ACL ACL three times - please contact rc-support@ucl.ac.uk" >&2
     exit 1
   fi
 done
