Add stderr redirect to new error messages.

diff --git a/createuser b/createuser
--- a/createuser
+++ b/createuser
@@ -15,9 +15,9 @@ fi
 # Check that the userid starts with a letter and is alphanumeric, 7 chars
 if echo $1 | grep -qE '^[[:lower:]][[:lower:][:digit:]]{6}$' ;
 then
-    echo "Valid user string: $1"
+    echo "Valid user string: $1" 1>&2
 else
-    echo "Invalid user string: $1"
+    echo "Invalid user string: $1" 1>&2
     echo "Run \"createuser userid\"" 1>&2
     exit 1
 fi 
