Added ypcat and getent modes.

diff --git a/realname b/realname
--- a/realname
+++ b/realname
@@ -1,32 +1,83 @@
-#!/bin/sh
+#!/usr/bin/env sh
 
 LDAPSEARCH_PATH=/usr/bin/ldapsearch
 
-if [ ! -x "$LDAPSEARCH_PATH" ]; then
-  echo "Error: this script requires ldapsearch." >&2
+
+while getopts ":eybh" opt; do
+  case $opt in
+    h)
+      echo -e "usage: $0 [options] username [username [...]]\n\n  Options:\n    -b    reverse lookup -- i.e. search for user names, not usernames (slow)\n    -y    ypcat mode -- requires ssh into socrates\n"
+      exit 0
+      ;;
+    b)
+      echo "Using reverse lookup -- this can be pretty slow." >&2
+      backwards_mode="y"
+      ;;
+    e)
+      echo "Using remote getent mode -- this can work for old usernames that are no longer in LDAP." >&2
+      lookup_mode="getent"
+      ;;
+    y)
+      echo "Using remote ypcat mode -- this can work for old usernames that are no longer in LDAP." >&2
+      lookup_mode="ypcat"
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 4
+      ;;
+  esac
+done
+
+shift $((OPTIND-1));
+
+if [ -z "$getent_mode" -a ! -x "$LDAPSEARCH_PATH" ]; then
+  echo -e "Error: this script requires ldapsearch.\n  (You might still be able to use ypcat or getent modes.)" >&2
   exit 3
 fi
 
 for name in "$@"; do
-  if [ "${#name}" -ne "7" ]; then
+  if [ "${#name}" -ne "7" -a -z "$backwards_mode" ]; then
     echo "Invalid username: \"${name}\"" >&2
     exit 2
   else
-    ldap_search=`$LDAPSEARCH_PATH \
-                        -x -LLL -y /shared/ucl/etc/ldappw \
-                        -H 'ldaps://openldap-auth2.ucl.ac.uk:636/' \
-                        -D  'cn=unixauth,ou=System Users,dc=uclusers,dc=ucl,dc=ac,dc=uk' \
-                        -b 'ou=Departments,dc=uclusers,dc=ucl,dc=ac,dc=uk' \
-                        "(cn=${name})" \
-                        | \
-                        sed -rn "s/^gecos: (.+)$/\1/p" \
-                        `
-
-    if [ -n "$ldap_search" ]; then
-      if [ $# -gt 1 ]; then
-        echo "${name}: ${ldap_search}"
+    if [ -z "$lookup_mode" ]; then
+      if [ -z "$backwards_mode" ]; then
+        search_key="cn"
+        display_key="gecos"
       else
-        echo "${ldap_search}"
+        search_key="gecos"
+        display_key="cn"
+      fi
+
+      search_result=`$LDAPSEARCH_PATH \
+                          -x -LLL -y /shared/ucl/etc/ldappw \
+                          -H 'ldaps://openldap-auth2.ucl.ac.uk:636/' \
+                          -D  'cn=unixauth,ou=System Users,dc=uclusers,dc=ucl,dc=ac,dc=uk' \
+                          -b 'ou=Departments,dc=uclusers,dc=ucl,dc=ac,dc=uk' \
+                          "(${search_key}=${name})" \
+                          | \
+                          sed -rn "s/^${display_key}: (.+)$/\1/p" \
+                          `
+
+    elif [ "$lookup_mode" == "getent" ]; then
+      if [ -z "$backwards_mode" ]; then
+        search_result=`ssh socrates.ucl.ac.uk "getent passwd $name" 2>/dev/null | awk -F: '{print $5;}'`
+      else 
+        search_result=`ssh socrates.ucl.ac.uk "getent passwd" 2>/dev/null | awk -F: '{print $5 ":" $1;}' | grep "$name" | awk -F: '{print $2;}'`
+      fi
+    elif [ "$lookup_mode" == "ypcat" ]; then
+      if [ -z "$backwards_mode" ]; then
+        search_result=`ssh socrates.ucl.ac.uk "/usr/local/rbin/ypcat passwd" 2>/dev/null | awk -F: '{print $1 ":" $5;}' | grep "^$name" 2>/dev/null | awk -F: '{print $2;}'`
+      else 
+        search_result=`ssh socrates.ucl.ac.uk "/usr/local/rbin/ypcat passwd" 2>/dev/null | awk -F: '{print $5 ":" $1;}' | grep "$name" 2>/dev/null  | awk -F: '{print $2;}'`
+      fi
+    fi
+
+    if [ -n "$search_result" ]; then
+      if [ $# -gt 1 ]; then
+        echo "${name}: ${search_result}"
+      else
+        echo "${search_result}"
       fi
     else
       echo "Error: no user found for username \"${name}\"" >&2
