Added mechanism to check perms and sufork if not running as ccspapp

diff --git a/remove_old_moduledirs b/remove_old_moduledirs
--- a/remove_old_moduledirs
+++ b/remove_old_moduledirs
@@ -1,7 +1,24 @@
 #!/usr/bin/env bash
 
+become_path=/shared/ucl/sysops/bin/become
+moduledirs_path=/shared/ucl/apps
+
+if (id -Gn | grep -v '\bccsprcop\b') && (whoami | grep -v ccspapp); then
+  echo "Error: user should be in ccsprcop group to use this script." >&2
+  exit 1
+fi
+
+if (whoami | grep -v ccspapp); then
+  echo "Becoming ccspapp and re-running..." >&2
+  $become_path ccspapp <<EOF
+  $0 "$@"
+EOF
+  exit
+fi
+  
+
 # v-- gets a list of all directories named .mf_* created more than 7 days ago
-dirs_to_remove=`find /shared/ucl/apps -maxdepth 1 -type d -name ".mf_*" -ctime +7`
+dirs_to_remove=`find $moduledirs_path -maxdepth 1 -type d -name ".mf_*" -ctime +7`
 
 num_dirs=`echo "$dirs_to_remove" | wc -l`
 
diff --git a/update_modules b/update_modules
--- a/update_modules
+++ b/update_modules
@@ -4,6 +4,21 @@
 #
 # by Ian Kirker, 2015
 
+moduledirs_path=/shared/ucl/apps
+
+if (id -Gn | grep -v '\bccsprcop\b') && (whoami | grep -v ccspapp); then
+  echo "Error: user should be in ccsprcop group to use this script." >&2
+  exit 1
+fi
+
+if (whoami | grep -v ccspapp); then
+  echo "Becoming ccspapp and re-running..." >&2
+  $become_path ccspapp <<EOF
+  $0 "$@"
+EOF
+  exit
+fi
+
 # Parse options (super-simple atm)
 
 if [[ -n "$1" ]]; then
@@ -15,6 +30,8 @@ fi
 
 # Don't try to continue if something breaks
 set -e
+
+cd $moduledirs_path
 
 if [[ ! -L "modulefiles" ]]; then
   if [[ "$force_update" != "y" ]]; then
@@ -29,7 +46,7 @@ if [[ ! -L "modulefiles" ]]; then
 fi
 
 
-# Config info
+# Repo config info
 
 branch="master"
 repo_url="https://github.com/UCL-RITS/rcps-modulefiles.git"
